# Generated by Django 5.0.4 on 2024-04-23 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('available_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254)),
                ('play_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.play')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_seats', models.IntegerField()),
                ('play_date', models.DateField()),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.play')),
            ],
        ),
    ]
