# Generated by Django 5.0.4 on 2024-04-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playbooking',
            unique_together={('user', 'play_date')},
        ),
    ]
